---
title: "data-vis"
author: "Hannah Fazekas"
date: "2/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

load packages 

```{r}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales) # install.packages("scales")
library(patchwork) # install.packages("patchwork")
```


```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```

```{r}
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink")) #%in% operator that looks for named values inside vector or dataframe. Is a value inside a set of things.

head(annual_esc)
```

# Data Visualization

## First look at the data

```{r}
ggplot(annual_esc, aes(x=Species, y=escapement)) + geom_col()
```

Changing the bar colors
```{r}
ggplot(annual_esc, aes(x=Species, y=escapement)) + geom_col(fill="blue")
```

Plot per region

```{r}
ggplot(annual_esc, aes(x=Species, y=escapement, fill=SASAP.Region)) + geom_col()
```

### Looking into the Kodiak region

Use piping to pass data for plots

```{r}
annual_esc %>% 
  filter(SASAP.Region == "Kodiak") %>% 
ggplot(aes(x = Year, y = escapement, color = Species)) + ylab("Escapement")+
    geom_line() + scale_y_continuous(labels=comma)+#scale_y_log10()+
    geom_point()+ggtitle("Annual Salmon Escapement in the Kodiak Region")+theme_bw()+ my_theme#theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom")


```

```{r}
#save theme into a variable:
my_theme <- theme_bw()+theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom", legend.title =element_blank())


```

Faceting plots

```{r}
ggplot(annual_esc, aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = comma) +
    facet_wrap(~SASAP.Region, scales = "free_y", ncol = 2) +
    ylab("Escapement") +
    my_theme

```



```{r}
p1<- ggplot(annual_esc, aes(x=Species, y=escapement)) + geom_col()

p2 <- ggplot(annual_esc, aes(x=Species, y=escapement)) + geom_col(fill="blue")

p3 <- ggplot(annual_esc, aes(x=Species, y=escapement)) + geom_col(fill="blue")

p1 / p2 / p3

p1+p2+p3

```


Write a function to compute the percentage of a number
```{r}
pct <- function(n,p) {
  n*p/100
}
```

Write a function to compute the percentage by default but you can compute permil
```{r}

pctvar <- function(n, p, c = 100) {
  n*p/c
} #n = number (num), p = percentage or ratio (num), c= denominator (num). 

pctvar(25,189)
pctvar(25,189,1000)



```


